TIMBERC=../timberc -c --target POSIX

tests:
	$(TIMBERC) Synstest.t Data/Functional/List.t Data/Objects/Stack.t Data/Objects/Dictionary.t Solitaire/Card.t Solitaire/CardPile.t AbstractStack.t AbstractStackClient.t  Observer.t ImportChain1.t ImportChain2.t ImportChain3.t Conflict.t ConflictClient.t SizedPoint.t SizedPoint2.t Tail.t Twice.t Primes.t Array0.t Histo.t Matrix.t HashTable.t Timer.t Reflex0.t


