tests:
	timberc -c Synstest.t Solitaire.Card.t Solitaire.CardPile.t AbstractStack.t AbstractStackClient.t  Observer.t ImportChain1.t ImportChain2.t ImportChain3.t Conflict.t ConflictClient.t SizedPoint.t SizedPoint2.t Tail.t Twice.t NoInteraction.t Array0.t Histo.t HistoClient.t Matrix.t  ManySimpleConstraints.t KindleArities.t Pointed.t Cyclic.t StructPat.t Binary.t Binary2.t  A.t B1.t B2.t C1.t C2.t C3.t C4.t

local:
	../timberc -c Synstest.t Solitaire.Card.t Solitaire.CardPile.t AbstractStack.t AbstractStackClient.t  Observer.t ImportChain1.t ImportChain2.t ImportChain3.t Conflict.t ConflictClient.t SizedPoint.t SizedPoint2.t Tail.t Twice.t NoInteraction.t Array0.t Histo.t HistoClient.t Matrix.t  ManySimpleConstraints.t KindleArities.t Pointed.t Cyclic.t StructPat.t Binary.t Binary2.t  A.t B1.t B2.t C1.t C2.t C3.t C4.t
